name: MethFinder
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2024.3.11
  - exceptiongroup=1.2.0
  - iniconfig=1.1.1
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.3
  - openssl=1.1.1w
  - packaging=23.2
  - pip=23.3.1
  - pluggy=1.0.0
  - pytest=7.4.0
  - python=3.9.12
  - readline=8.1.2
  - setuptools=68.0.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tomli=2.0.1
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==2.1.0
    - astor==0.8.1
    - asttokens==2.4.1
    - bio==1.6.0
    - biopython==1.81
    - biothings-client==0.3.1
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - clarabel==0.9.0
    - click==8.1.8
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - comm==0.2.0
    - contextlib2==21.6.0
    - contourpy==1.2.0
    - cvxpy==1.5.3
    - cycler==0.12.1
    - debugpy==1.8.0
    - decorator==5.1.1
    - dgl==1.1.3
    - dgllife==0.3.2
    - ecos==2.0.14
    - et_xmlfile==2.0.0
    - executing==2.0.1
    - filelock==3.11.0
    - flashtorch==0.1.0
    - fonttools==4.46.0
    - fsspec==2023.12.1
    - future==0.18.3
    - gensim==4.3.2
    - gprofiler-official==1.0.0
    - h5py==3.10.0
    - hiddenlayer==0.3
    - huggingface-hub==0.19.4
    - hyperopt==0.2.7
    - idna==3.6
    - importlib-metadata==7.0.0
    - importlib-resources==6.1.1
    - intervaltree==3.1.0
    - iprogress==0.4
    - ipykernel==6.27.1
    - ipython==8.18.1
    - ipywidgets==8.1.7
    - jedi==0.19.1
    - joblib==1.3.2
    - json-tricks==3.17.3
    - keras==3.1.1
    - kiwisolver==1.4.5
    - kneed==0.8.5
    - llvmlite==0.42.0
    - logomaker==0.8
    - markdown-it-py==3.0.0
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - ml-dtypes==0.4.0
    - mygene==3.2.2
    - namex==0.0.7
    - nest-asyncio==1.5.8
    - networkx==3.2.1
    - nni==3.0
    - numba==0.59.1
    - numpy==1.26.2
    - nvidia-ml-py==12.535.133
    - openpyxl==3.1.5
    - optree==0.11.0
    - osqp==0.6.7.post3
    - pandas==2.1.4
    - parso==0.8.3
    - pexpect==4.9.0
    - pillow==10.1.0
    - platformdirs==4.1.0
    - pooch==1.8.0
    - prettytable==3.9.0
    - prompt-toolkit==3.0.41
    - protobuf==3.20.3
    - psutil==5.9.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py4j==0.10.9.7
    - pygments==2.17.2
    - pympler==1.0.1
    - pynndescent==0.5.12
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pythonwebhdfs==0.2.3
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - qdldl==0.1.7.post4
    - rdkit==2023.9.5
    - regex==2023.10.3
    - requests==2.31.0
    - responses==0.24.1
    - rich==13.7.1
    - sacremoses==0.1.1
    - safetensors==0.4.1
    - schema==0.7.5
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - scs==3.2.7
    - seaborn==0.13.0
    - sentencepiece==0.1.99
    - shap==0.47.0
    - simplejson==3.19.2
    - six==1.16.0
    - slicer==0.0.8
    - smart-open==7.0.4
    - sortedcontainers==2.4.0
    - speedtest-cli==2.1.3
    - stack-data==0.6.3
    - threadpoolctl==3.2.0
    - tokenizers==0.15.0
    - torch==1.12.0+cu116
    - torchaudio==0.12.0+cu116
    - torchvision==0.13.0+cu116
    - tornado==6.4
    - tqdm==4.66.1
    - traitlets==5.14.0
    - transformers==4.35.2
    - typeguard==4.1.2
    - typing_extensions==4.9.0
    - umap-learn==0.5.7
    - urllib3==2.1.0
    - wcwidth==0.2.12
    - websockets==12.0
    - widgetsnbextension==4.0.14
    - wrapt==1.16.0
    - xlrd==2.0.1
    - zipp==3.17.0

